"""Add email verification support

Revision ID: 004
Revises: 003
Create Date: 2025-11-11 20:00:54.657458

"""
from alembic import op
import sqlalchemy as sa


revision = '004'
down_revision = '003'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add email_verified column if it doesn't exist
    conn = op.get_bind()
    conn.execute(sa.text("""
        DO $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM information_schema.columns
                WHERE table_name='users' AND column_name='email_verified'
            ) THEN
                ALTER TABLE users ADD COLUMN email_verified BOOLEAN DEFAULT false NOT NULL;
            END IF;
        END $$;
    """))

    # Create email_verification_tokens table if it doesn't exist
    conn.execute(sa.text("""
        CREATE TABLE IF NOT EXISTS email_verification_tokens (
            id VARCHAR(50) NOT NULL PRIMARY KEY,
            user_id VARCHAR(50) NOT NULL,
            token_hash VARCHAR(64) NOT NULL,
            expires_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
            used BOOLEAN DEFAULT false NOT NULL,
            created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL
        );
    """))

    # Create indexes if they don't exist
    conn.execute(sa.text("""
        CREATE INDEX IF NOT EXISTS ix_email_verification_tokens_user_id
        ON email_verification_tokens (user_id);
    """))
    conn.execute(sa.text("""
        CREATE UNIQUE INDEX IF NOT EXISTS ix_email_verification_tokens_token_hash
        ON email_verification_tokens (token_hash);
    """))
    conn.execute(sa.text("""
        CREATE INDEX IF NOT EXISTS ix_email_verification_tokens_expires_at
        ON email_verification_tokens (expires_at);
    """))
    conn.execute(sa.text("""
        CREATE INDEX IF NOT EXISTS ix_email_verification_tokens_used
        ON email_verification_tokens (used);
    """))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop email_verification_tokens table
    op.drop_index(op.f('ix_email_verification_tokens_used'), table_name='email_verification_tokens')
    op.drop_index(op.f('ix_email_verification_tokens_expires_at'), table_name='email_verification_tokens')
    op.drop_index(op.f('ix_email_verification_tokens_token_hash'), table_name='email_verification_tokens')
    op.drop_index(op.f('ix_email_verification_tokens_user_id'), table_name='email_verification_tokens')
    op.drop_table('email_verification_tokens')

    op.drop_column('users', 'email_verified')
    # ### end Alembic commands ###
